/// 货币代码 → 国旗 emoji（用于汇率列表展示）
String currencyFlagEmoji(String currencyCode) {
  final country = _kCurrencyToCountry[currencyCode.toUpperCase()];
  if (country == null || country.length != 2) return '🏳️';
  return country.toUpperCase().replaceAllMapped(
        RegExp(r'[A-Z]'),
        (match) => String.fromCharCode(match.group(0)!.codeUnitAt(0) + 127397),
      );
}

const _kCurrencyToCountry = {
  'CNY': 'CN',
  'CNH': 'CN',
  'USD': 'US',
  'EUR': 'EU',
  'GBP': 'GB',
  'JPY': 'JP',
  'HKD': 'HK',
  'KRW': 'KR',
  'SGD': 'SG',
  'TWD': 'TW',
  'AUD': 'AU',
  'CAD': 'CA',
  'CHF': 'CH',
  'NZD': 'NZ',
  'THB': 'TH',
  'MYR': 'MY',
  'INR': 'IN',
  'RUB': 'RU',
  'BRL': 'BR',
  'MXN': 'MX',
  'ZAR': 'ZA',
  'SEK': 'SE',
  'NOK': 'NO',
  'DKK': 'DK',
  'PLN': 'PL',
  'TRY': 'TR',
  'AED': 'AE',
  'SAR': 'SA',
  'ILS': 'IL',
  'PHP': 'PH',
  'IDR': 'ID',
  'VND': 'VN',
  'XOF': 'SN',
  'XAF': 'CM',
  'XPF': 'PF',
  'XCD': 'AG',
  'ARS': 'AR',
  'CLP': 'CL',
  'COP': 'CO',
  'PEN': 'PE',
  'EGP': 'EG',
  'NGN': 'NG',
  'KES': 'KE',
  'PKR': 'PK',
  'BDT': 'BD',
  'UAH': 'UA',
  'CZK': 'CZ',
  'HUF': 'HU',
  'RON': 'RO',
  'BGN': 'BG',
  'HRK': 'HR',
  'ISK': 'IS',
  'MOP': 'MO',
  'GHS': 'GH',
  'MAD': 'MA',
  'QAR': 'QA',
  'KWD': 'KW',
  'BHD': 'BH',
  'OMR': 'OM',
  'JOD': 'JO',
  'LBP': 'LB',
  'IQD': 'IQ',
  'GNF': 'GN',
  'GMD': 'GM',
  'GTQ': 'GT',
  'GYD': 'GY',
};
